name: Release

on:
  push:
    tags:
    - '*.*.*'
jobs:
  build:
    environment: nuget
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Setup dotnet 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build and pack package
      shell: bash
      run: ./pack.sh
    - name: Publish to nuget
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      shell: bash
      run: ./publish.sh $NUGET_API_KEY $RELEASE_VERSION